Quiz_Project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    
    path('admin/', admin.site.urls),
    path('', include('home_app.urls')),
    path('auth_app/', include('auth_app.urls')),
    path('quiz_app/', include('quiz_app.urls')),
    
]

auth_app/urls.py
from django.urls import path
from auth_app import views

urlpatterns = [
    
    path('registration/', views.authregistration, name = 'registration'),
    path('login', views.authlogin, name = 'login'),
    path('logout/', views.authlogout, name = 'logout'),
    
]

quiz_app/urls.py
from django.urls import path
from quiz_app import views

app_name = "quiz_app"

urlpatterns = [
    
    path('profile/', views.profile, name='profile'),
    path('quiz_questions/<int:category_id>/', views.quiz_questions, name='quiz_questions'),
    path('leader/', views.leader, name='leader'),
    
]

quiz_app/models.py
from django.db import models

# Create your models here.


'''Created class QuizName for type of quiz'''

class QuizName(models.Model):
    quiz_name = models.CharField(max_length=200, blank=False)

    
    def __str__(self):
        return self.quiz_name
    
    class Meta:
        db_table = "QuizName"
        

'''Created class QuestionModel for quiz questions and answers and hint'''

class QuestionModel(models.Model):
    question = models.CharField(max_length=200, blank=False)
    option1 = models.CharField(max_length=200, blank=False)
    option2 = models.CharField(max_length=200, blank=False)
    option3 = models.CharField(max_length=200, blank=False)
    option4 = models.CharField(max_length=200, blank=False)
    answer = models.CharField(max_length=200, blank=False)
    category = models.ForeignKey(QuizName, on_delete=models.CASCADE)
    
    class Meta:
        db_table = "QuestionModel"
        
    def __str__(self):
        return str(self.category) + " " + self.question
   
   
'''Created class Leaderboard to display all quiz results'''

class Leaderboard(models.Model):
    name = models.CharField(max_length=200, blank=False)
    quiz_name = models.CharField(max_length=200, blank=False)
    total = models.CharField(max_length=200, blank=False)
    correct = models.CharField(max_length=200, blank=False)
    incorrect = models.CharField(max_length=200, blank=False)
    percentage = models.CharField(max_length=200, blank=False)
    
    def __str__(self):
        return self.name
    
    class Meta:
        db_table = "Quiz_Leaderboard"
      

quiz_app/forms.py
from django import forms
from quiz_app.models import QuestionModel
class quiz_form(forms.ModelForm):
    class Meta:
        model = QuestionModel
        fields = '__all__'

quiz_app/views.py
from django.shortcuts import render
from django.http import HttpResponse
from quiz_app import forms
from quiz_app.models import QuizName, QuestionModel, Leaderboard
from django.core.mail import send_mail
from home_app.models import contactform
from home_app.views import contact
from auth_app.models import User
from home_app.models import contactform
from django.core.mail import EmailMultiAlternatives
from django.template.loader import render_to_string
from django.utils.html import strip_tags


# Create your views here.

'''Function for profile page when user login'''
def profile(request):
    quiz_list = QuizName.objects.order_by('quiz_name')    
    list_of_Quiz = {
        'text_1': "This is List of Quiz",
        'quiz_list': quiz_list,
        }
    return render(request, 'quiz_app/profile.html', context = list_of_Quiz)

'''Function for quiz'''
# email=contactform.objects.POST.get('email')
def quiz_questions(request, category_id):

    if request.method == 'POST':
        '''Get the questions from the QuestionModel Model based on catagory using forign key'''
        u_email=request.user.email
        quiz_questions_list = QuestionModel.objects.filter(category=category_id).all()
        score = 0
        wrong = 0
        correct = 0
        total = 0
        for row in quiz_questions_list:
            quiz_name = row.category
            total += 1
            if row.answer == request.POST.get(row.question):
                score += 1 # For correct answers 10 marks added
                correct += 1
            else:
                wrong += 1 # For wrong answers 3 marks deducted
                score -= 0
        quiz_two_percent = (score/total) * 100
        quiz_result = {
            'user_name':request.user.username,
            'quiz_name':quiz_name,
            'score': score,
            'correct': correct,
            'wrong': wrong,
            'percent': quiz_two_percent,
            'total': total,
        }
        '''Saving the Quiz result to database'''
        user_name = request.user.username
        result = Leaderboard(name = user_name, quiz_name = quiz_name, 
                             total = total, correct= correct, 
                             incorrect = wrong, percentage =quiz_two_percent)
        result.save()
        
        # send_mail("Your Quiz Result",
        #           f"{quiz_result}",
        #           "namratagaland@gmail.com",
        #           [u_email,])
        html_content=render_to_string('quiz_app/certificate.html',{'username':request.user.username,'quiz_name':quiz_name,'percent': quiz_two_percent})
        c_text=strip_tags(html_content)
        c_email=EmailMultiAlternatives(
            "Your Quiz Result",
            c_text,
            "maheshhn014@gmail.com",
            [u_email,'harshith1996nov@gmail.com',]
        )
        c_email.attach_alternative(html_content,'text/html')
        c_email.send()


        '''Email part'''
        return render(request,'quiz_app/result.html', context = quiz_result)
        
    else:
        '''Get the questions from the QuestionModel Model based on catagory using forign key'''
        # pk = primary key
        quiz_list = QuizName.objects.get(pk=category_id) 
        quiz_questions_list = QuestionModel.objects.filter(category=category_id).all()
        for row in quiz_questions_list:
            quiz_name = row.category
        quiz_questions = {'quiz_list': quiz_list,
                          'quiz_questions_list': quiz_questions_list,
                          'id': quiz_list.id,
                          'quiz_name':quiz_name,
                }
        return render(request, 'quiz_app/quiz.html', context = quiz_questions)
 
'''Function to display the Leaderboard'''
def leader(request):
    result_list_board = Leaderboard.objects.all().order_by('percentage')
    dict = {'heading': "The Last Quizz Results of the Users",
            'result_list': result_list_board}
    return render(request, 'quiz_app/leader.html', context = dict)


# Create your views here.


def home1(Request):
    return render(Request, "quiz_app/quiz.html")

def Question(Request):
    form = forms.quiz_form()
    if Request.method == 'POST':
       form = forms.quiz_form(Request.POST)
       if form.is_valid():
           form.save(commit=True)
           return HttpResponse("<h1> Details Updated Successfully</h1>")
       else:
           print("Form is invalid")
    return render(Request, "quiz_app/quiz.html", context=dict({'form_d': form}))
# return render(Request,"Train_Info/train_info.html",{'form_d':form})

templates/quiz_app/certificate.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="certifi.css">
    <title></title>
  </head>
  <body>

  <div style="width:800px; height:600px; padding:20px; text-align:center; border: 10px solid #787878">
  <div style="width:750px; height:550px; padding:20px; text-align:center; border: 5px solid #787878">
         <span style="font-size:50px; font-weight:bold">Certificate of Completion</span>
         <br><br>
         <span style="font-size:25px"><i>This is to Awarded to</i></span>
         <br><br>
         <span style="font-size:30px"><b>{{username}}</b></span><br/><br/>
         <span style="font-size:25px"><i>in recognition of achieving</i></span> <br/><br/>
         <span style="font-size:30px">quizz in {{quiz_name}}</span> <br/><br/>
         <span style="font-size:20px">with score of <b>{{percent}}%</b></span> <br/><br/><br/><br/>
         <span style="font-size:25px"><i>Certified by The Great</i></span><br>

        <span style="font-size:30px">Mahi Shetty</span>
  </div>
  </div>
  </body>
</html>

templates/quiz_app/leader.html
{% extends 'layout.html' %}

{% block title %}

Leaderboard

{% endblock %}

{% block body_block %}

<br>

<h1 style="text-align:center; color:white;"> {{ heading }} </h1>

<hr>

<style>

    .table-bordered > tbody > tr > td, .table-bordered > tbody > tr > th, 
    .table-bordered > tfoot > tr > td, .table-bordered > tfoot > tr > th, 
    .table-bordered > thead > tr > td, .table-bordered > thead > tr > th 
    {
        border: 1px white;
    }

</style>


<table class="table table-bordered" >



    <tr>
        <th>Name</th>
        <th>Quiz Name</th>
        <th>Total Questions</th>
        <th>Correct Answers</th>
        <th>Incorrect Answers</th>
        <th>Score (In % )</th>
    </tr>

    {% for row in result_list %}

    <tr>

        <td> {{ row.name }} </td>
        <td> {{ row.quiz_name }} </td>
        <td> {{ row.total }} </td>
        <td> {{ row.correct }} </td>
        <td> {{ row.incorrect }} </td>
        <td> {{ row.percentage }} </td>

    </tr>

    {% endfor %}

</table>

<hr>

{% endblock %}

templates/quiz_app/profile.html
{% extends 'layout.html' %}

{% block title %}

Profile Page

{% endblock %}


{% block body_block %}

<br>

<div style="text-align:center;">

    <h2 style="color:#FFF;">>Welcome {{user.username}} For Skill Test </h2>

    <h3 style="color:#FFF;"></h3>

    <h3 style="color:#FFF;">>Each Quiz contain 20 questions {{user.email}}</h3>

    <h3 style="color:#FFF;">>For correct answer 1 marks for each question </h3>

    <h3 style="color:#FFF;">>For wrong answers 0 deducted for each question</h3>

    <h3 style="color:#FFF;">>Take a quiz and check your knowledge</h3>

    <h3 style="color:#FFF;">>All the best for your Quiz <b>{{user.username}}</b></h3>

    <h2 style="color:white;">{{ text_1 }}</h2>


        {% if quiz_list %}

            {% for name in quiz_list %}


            <h3><a href="{% url 'quiz_app:quiz_questions' category_id=name.id %}"><li>{{ name.quiz_name }}</li></a></h3>

            {% endfor %}

        {% else %}

            <h3>No Quiz in the List</h3>

        {% endif %}



</div>





{% endblock %}

templates/quiz_app/quiz.html
{% extends 'layout.html' %}

{% block title %}
Quiz Page
{% endblock %}

{% block body_block %}

<br>

<div class="container ">

    <h1 style="color:black;">Welcome to {{ quiz_name }} Quiz</h1>

    <hr>

    <form method='post'>

        {% csrf_token %}
        {% for row in quiz_questions_list %}

        <strong><label for="question"><b>{{row.question}}</b></label></strong>

        <div class="form-check">

            <div class="form-check">

                <input class="form-check-input" type="radio" name="{{row.question}}" value="option1">
                <label class="form-check-label" style="color:#fff"><b>{{row.option1}}</b></label>

            </div>

            <div class="form-check">

                <input class="form-check-input" type="radio" name ="{{row.question}}" value="option2">
                <label class="form-check-label" style="color:#fff"><b>{{row.option2}}</b></label>

            </div>

            <div class="form-check">

                <input class="form-check-input" type="radio" name="{{row.question}}" value="option3">
                <label class="form-check-label" style="color:#fff"><b>{{row.option3}}</b></label>

            </div>

            <div class="form-check">

                <input class="form-check-input" type="radio" name="{{row.question}}" value="option4">
                <label class="form-check-label" style="color:#fff"><b>{{row.option4}}</b></label>
            </div>
                    
            <br>

        </div>

        {% comment %} Pop Up For Hint Start {% endcomment %}


            <div class="">

                <style media="screen">
            
                .button {
                    font-size: 1em;
                    padding: 10px;
                    color: black;
                    border: 2px solid #06D85F;
                    border-radius: 20px/50px;
                    text-decoration: none;
                    cursor: pointer;
                    transition: all 0.3s ease-out;
                }
                .button:hover {
                    background: #06D85F;
                }
            
                .overlay {
                    position: fixed;
                    top: 0;
                    bottom: 0;
                    left: 0;
                    right: 0;
                    background: rgba(0, 0, 0, 0.7);
                    transition: opacity 500ms;
                    visibility: hidden;
                    opacity: 0;
                }
                .overlay:target {
                    visibility: visible;
                    opacity: 1;
                }
            
                .popup {
                    margin: 70px auto;
                    padding: 20px;
                    background: #fff;
                    border-radius: 5px;
                    width: 30%;
                    position: relative;
                    transition: all 5s ease-in-out;
                }
            
                .popup h2 {
                    margin-top: 0;
                    color: #333;
                    font-family: Tahoma, Arial, sans-serif;
                }
                .popup .close {
                    position: absolute;
                    top: 20px;
                    right: 30px;
                    transition: all 200ms;
                    font-size: 30px;
                    font-weight: bold;
                    text-decoration: none;
                    color: #333;
                }
                .popup .close:hover {
                    color: #06D85F;
                }
                .popup .content {
                    max-height: 30%;
                    overflow: auto;
                }
            
                @media screen and (max-width: 700px){
                    .box{
                    width: 70%;
                    }
                    .popup{
                    width: 70%;
                    }
                }
            
            
                </style>
            
<!--                <a class="button" href="#popup1">Hint</a>-->
            
                <div id="popup1" class="overlay">

                    <div class="popup">

                        <h2>The Hint Is</h2>
                        <a class="close" href="#">&times;</a>
                        <div class="content">
                            {{row.hint}}
                        </div>
                    </div>

                </div>
            
            </div>

        {% comment %} Pop Up For Hint End {% endcomment %}

        <br>
        
        {% endfor %}
        
        <button type="submit" class="btn btn-primary">Submit</button>

    </form>

</div>

<br>
<hr>




{% endblock %}

templates/quiz_app/result.html
{% extends 'layout.html' %}

{% block title %}

Result Page

{% endblock %}

{% block body_block %}

<div class="container">
        
    <div class="card-columns" style="padding: 10px; margin: 20px;">

        <div class="card" style="width: 40rem; border:3px black solid">
            
            <div class="card-body">

                <h3><b>Skill Test Quiz-1 Result</b></h3>

                <h5 class="card-title"><b>Score :</b> {{score}}</h5>

                <p class="card-text"><b>Percentage :</b> {{percent}}%</p>
                <p class="card-text"><b>Correct answers :</b> {{correct}}</p>
                <p class="card-text"><b>Incorrect answers :</b> {{wrong}}</p>
                <p class="card-text"><b>Total questions :</b> {{total}}</p>

                <h5>All the best for next quiz!</h5>

            </div>

        </div>

    </div>

</div>

<h3 style="color:white;">Click on View to get the Leaderboard of the quiz</h3>

<a class="nav-link active" aria-current="page" href="{% url 'quiz_app:leader' %}">View</a>

<h3 style="color:white;">Certificate has been Send to Your registered mail ID</h3>



{% endblock %}