Quiz_Project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    
    path('admin/', admin.site.urls),
    path('', include('home_app.urls')),
    path('auth_app/', include('auth_app.urls')),
    path('quiz_app/', include('quiz_app.urls')),
    
]

auth_app/urls.py
from django.urls import path
from auth_app import views

urlpatterns = [
    
    path('registration/', views.authregistration, name = 'registration'),
    path('login', views.authlogin, name = 'login'),
    path('logout/', views.authlogout, name = 'logout'),
    
]

quiz_app/urls.py
from django.urls import path
from quiz_app import views

app_name = "quiz_app"

urlpatterns = [
    
    path('profile/', views.profile, name='profile'),
    path('quiz_questions/<int:category_id>/', views.quiz_questions, name='quiz_questions'),
    path('leader/', views.leader, name='leader'),
    
]

templates/layout.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">


    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>

        {% block title %}


        {% endblock %}

    </title>

<!--    <link rel="stylesheet" href="{% static 'css/style.css' %}">-->


    <style>


   body {

         background-image:url('{% static 'css/pysch14.jpg' %}');
        background-repeat:no-repeat;
        background-size:130%;
        background-attachment: fixed;
        }

        .navbar-brand
        {
        font-family: Copperplate, "Copperplate Gothic Light", fantasy;
        font-size: 18px;
        font-style: normal;
        font-variant: normal;

        }

        .nav-item
        {
            font-family: 'Copperplate', 'Papyrus', 'fantasy';
            font-size: 25px;
        }

    </style>

  </head>


<body>


<!-- Navbar -->
<nav class="navbar navbar-expand-lg navbar-light bg-dark">


    <div class="container-fluid">
<!--        <video autoplay loop muted playsinline class="bg-video">-->
<!--            <source src="bg\bg-quizz.webm" type="video/webm">-->

<!--        </video>-->
<!--        <video  autoplay loop muted playsinline>-->
<!--        <source src="css\bg-video.mp4" type="video/mp4" class="back">-->
<!--      </video>-->
      <a class="navbar-brand" href="#"><b>💡Basic Skills Quiz💡</b></a>

      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">

            <ul class="navbar-nav me-auto mb-2 mb-lg-0 ">

                <li class="nav-item px-4">
                    <a class="nav-link active" aria-current="page" href="{% url 'home' %}">🏡Home</a>
                </li>

                <li class="nav-item px-4">
                    <a class="nav-link active" href="{% url 'about' %}">❓About</a>
                </li>

                <li class="nav-item px-4">
                    <a class="nav-link active" aria-current="page" href="{% url 'contact' %}">☎️Contact</a>
                </li>

            </ul>

        </div>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">

            <ul class="navbar-nav me-auto mb-2 mb-lg-0 mb-lg-0 ml-auto">

                {% if user.is_authenticated%}

                <li class="nav-item px-4">
                    <a class="nav-link active" aria-current="page"  href="{% url 'logout' %}">Logout</a>
                </li>

                {% else %}

                <li class="nav-item px-4">
                    <a class="nav-link active" aria-current="page"  href="{% url 'login' %}">📃Login</a>
                </li>

                {% endif %}

                {% if user.is_authenticated %}

                <li class="nav-item px-4 ">
                    <a class="nav-link active" aria-current="page" href="{% url 'quiz_app:profile' %}">👥{{user.username}}</a>
                </li>

                {% else %}

                <li class="nav-item px-4 ">
                    <a class="nav-link active" aria-current="page" href="{% url 'registration' %}">📑Register</a>
                </li>

                {% endif %}


            </ul>

        </div>

    </div>

</nav>


<div class="container">

    {% block body_block %}


    {% endblock %}

</div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
<!--    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>-->
<!--    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>-->
<!--    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>-->


    </body>

</html>